# .golangci.yml - Linter configuration compatible with Go 1.24
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: "1.24"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/motain
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  unused:
    go: "1.24"
  staticcheck:
    go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - dupl
    - goconst
  disable:
    - goanalysis_metalinter  # Disable problematic linter
    - gocritic              # Can be problematic with newer Go versions
    - funlen               # Disable overly strict length checks

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error