---
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - severity